export const GENRES = [
  "Ambient",
  "Americana",
  "Blues",
  "Bluegrass",
  "Classical",
  "Country",
  "DJ/Electronic",
  "Electronic",
  "Emo",
  "Experimental",
  "Folk",
  "Funk",
  "Garage",
  "Hardcore",
  "Hip-Hop",
  "Indie",
  "Jazz",
  "Latin",
  "Metal",
  "Pop",
  "Post-Punk",
  "Punk",
  "R&B",
  "Reggae",
  "Rock",
  "Shoegaze",
  "Singer-Songwriter",
  "Ska",
  "Soul",
  "World",
] as const;

export type Genre = (typeof GENRES)[number];

export const DEAL_TYPES = [
  { value: "flat_fee", label: "Flat Fee" },
  { value: "door_split", label: "Door Split" },
  { value: "ticket_split", label: "Ticket Split" },
  { value: "bar_split", label: "Bar Split" },
  { value: "other", label: "Other" },
] as const;

export type DealType = (typeof DEAL_TYPES)[number]["value"];

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
] as const;
