import { v, ConvexError } from "convex/values";
import { query, mutation } from "./_generated/server";
import { requireUser } from "./lib/auth";
import { Doc } from "./_generated/dataModel";

export function generateContractText(
  booking: {
    date: string;
    startTime?: string;
    endTime?: string;
    loadInTime?: string;
    setLength?: number;
    dealType: string;
    amount?: number;
    splitPercentage?: number;
  },
  venue: { name: string; location: { city: string; state: string; address?: string } },
  musician: { bandName: string }
) {
  const dealLabels: Record<string, string> = {
    flat_fee: "Flat Fee",
    door_split: "Door Split",
    ticket_split: "Ticket Split",
    bar_split: "Bar Split",
    other: "Other",
  };

  const lines = [
    "LIVE MUSIC PERFORMANCE AGREEMENT",
    "",
    `Date: ${booking.date}`,
    booking.startTime ? `Start Time: ${booking.startTime}` : null,
    booking.endTime ? `End Time: ${booking.endTime}` : null,
    booking.loadInTime ? `Load-in Time: ${booking.loadInTime}` : null,
    booking.setLength ? `Set Length: ${booking.setLength} minutes` : null,
    "",
    "VENUE",
    `Name: ${venue.name}`,
    `Location: ${venue.location.address ? `${venue.location.address}, ` : ""}${venue.location.city}, ${venue.location.state}`,
    "",
    "ARTIST",
    `Name: ${musician.bandName}`,
    "",
    "COMPENSATION",
    `Deal Type: ${dealLabels[booking.dealType] ?? booking.dealType}`,
    booking.amount ? `Amount: $${booking.amount}` : null,
    booking.splitPercentage ? `Split: ${booking.splitPercentage}%` : null,
    "",
    "TERMS",
    "1. Either party may cancel with 48 hours notice without penalty.",
    "2. The venue agrees to provide a sound system and basic lighting.",
    "3. The artist agrees to perform for the agreed duration.",
    "4. Payment is due at the end of the performance unless otherwise arranged.",
    "",
    "DISCLAIMER",
    "This agreement is generated by Bandwire for informational purposes. Both parties should review and acknowledge the terms above.",
  ];

  return lines.filter((l) => l !== null).join("\n");
}

export const listMine = query({
  args: {},
  handler: async (ctx) => {
    const user = await requireUser(ctx);

    let bookings: Doc<"bookings">[];
    if (user.role === "venue") {
      bookings = await ctx.db
        .query("bookings")
        .withIndex("by_venueUserId", (q) => q.eq("venueUserId", user._id))
        .order("desc")
        .collect();
    } else {
      bookings = await ctx.db
        .query("bookings")
        .withIndex("by_musicianUserId", (q) =>
          q.eq("musicianUserId", user._id)
        )
        .order("desc")
        .collect();
    }

    return await Promise.all(
      bookings.map(async (booking) => {
        const venue = await ctx.db.get(booking.venueId);
        const musician = await ctx.db.get(booking.musicianId);
        return {
          ...booking,
          venueName: venue?.name ?? "Unknown",
          musicianBandName: musician?.bandName ?? "Unknown",
        };
      })
    );
  },
});

export const getById = query({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, args) => {
    const user = await requireUser(ctx);
    const booking = await ctx.db.get(args.bookingId);
    if (!booking) return null;

    if (
      booking.venueUserId !== user._id &&
      booking.musicianUserId !== user._id
    ) {
      throw new ConvexError("Not authorized");
    }

    const venue = await ctx.db.get(booking.venueId);
    const musician = await ctx.db.get(booking.musicianId);

    const contractText =
      venue && musician
        ? generateContractText(booking, venue, musician)
        : "Contract unavailable";

    return {
      ...booking,
      venueName: venue?.name ?? "Unknown",
      venueLocation: venue?.location,
      venueCapacity: venue?.capacity,
      musicianBandName: musician?.bandName ?? "Unknown",
      musicianLocation: musician?.location,
      contractText,
    };
  },
});

export const cancel = mutation({
  args: {
    bookingId: v.id("bookings"),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const user = await requireUser(ctx);
    const booking = await ctx.db.get(args.bookingId);
    if (!booking) throw new ConvexError("Booking not found");

    if (
      booking.venueUserId !== user._id &&
      booking.musicianUserId !== user._id
    ) {
      throw new ConvexError("Not authorized");
    }

    if (booking.status === "cancelled") {
      throw new ConvexError("Booking is already cancelled");
    }

    await ctx.db.patch(args.bookingId, { status: "cancelled" });
    await ctx.db.patch(booking.openDateId, { status: "open" });

    // Notify the other party
    const otherUserId =
      booking.venueUserId === user._id
        ? booking.musicianUserId
        : booking.venueUserId;

    const reasonText = args.reason ? ` Reason: ${args.reason}` : "";
    await ctx.db.insert("notifications", {
      userId: otherUserId,
      type: "booking_cancelled",
      title: "Booking Cancelled",
      message: `A booking for ${booking.date} has been cancelled.${reasonText}`,
      relatedBookingId: booking._id,
      isRead: false,
      createdAt: Date.now(),
    });

    return null;
  },
});

export const acknowledgeContract = mutation({
  args: { bookingId: v.id("bookings") },
  handler: async (ctx, args) => {
    const user = await requireUser(ctx);
    const booking = await ctx.db.get(args.bookingId);
    if (!booking) throw new ConvexError("Booking not found");

    if (booking.venueUserId === user._id) {
      await ctx.db.patch(args.bookingId, {
        contractAcknowledgedByVenue: true,
      });
    } else if (booking.musicianUserId === user._id) {
      await ctx.db.patch(args.bookingId, {
        contractAcknowledgedByMusician: true,
      });
    } else {
      throw new ConvexError("Not authorized");
    }

    return null;
  },
});
